# Generated by Django 5.2.12 on 2026-03-27 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='filmak_filma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izenburua', models.CharField(max_length=100)),
                ('zuzendaria', models.CharField(max_length=60)),
                ('urtea', models.IntegerField()),
                ('generoa', models.CharField(max_length=2)),
                ('sinopsia', models.CharField(max_length=500)),
                ('bozkak', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bozkatzailea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='filmak_bozkatzaileak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erabiltzailea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmak.bozkatzailea')),
            ],
        ),
    ]
