# Generated by Django 6.0.3 on 2026-03-28 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bozkatzailea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filmak_filma',
            name='bozkak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filmak_filma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='filmak_bozkatzailea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmak.bozkatzailea')),
                ('filma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmak.filmak_filma')),
            ],
        ),
        migrations.DeleteModel(
            name='filmak_bozkatzaileak',
        ),
    ]
