# Generated by Django 5.2.12 on 2026-03-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmak', '0002_alter_bozkatzailea_id_alter_filmak_filma_bozkak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bozkatzailea',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filmak_bozkatzailea',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filmak_filma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='filmak_bozkatzailea',
            constraint=models.UniqueConstraint(fields=('erabiltzailea', 'filma'), name='unique_vote_per_user_per_film'),
        ),
    ]
